//hey! Get out of here, you cheater! >:C

var currentSong;

var songList = [
	{id: 1, question: "Who is the artist of this song?", options: ["Nick Drake", "Elliot Smith", "Daniel Johnston", "Mount Eerie"], answer: "Nick Drake", lyrics: "I saw it written and I saw it say/A pink moon is on it's way/And none of you stand so tall/Pink moon gonna get ye all", half: ["Nick Drake", "Elliot Smith"], fullanswer: "Pink Moon - Nick Drake", songFile: "samp1"},
	{id: 2, question: "What is the name of this song?", options: ["Ventura Highway", "Tin Man", "Sister Golden Hair", "What Road"], answer: "Ventura Highway", lyrics: "Chewing on a piece of grass, walking down the road/Tell me, how long you gonna stay here Joe?/Some people say this town don't look good in snow/You don't care, I know", half: ["Ventura Highway", "Sister Golden Hair"], fullanswer: "Ventura Highway - America", songFile: "samp2"},
	{id: 3, question: "Who is the artist of this song?", options: ["Fiona Apple", "Kate Bush", "Angel Olsen", "The Knife"], answer: "Fiona Apple", lyrics: "If what I am is what I am/'Cause I does what I does/Then brother get back, 'cause my breast's gonna bust open/The rib is the shell/And a heart is the yolk/And I just made a meal for us both to choke on", half: ["Fiona Apple", "Angel Olsen"], fullanswer: "Every Single Night - Fiona Apple", songFile: "samp3"},
	{id: 4, question: "Who is the artist of this song?", options: ["The Kinks", "The Beatles", "The Monks", "The The"], answer: "The Kinks", lyrics: "I don't where I'm going, I don't want to see/I feel the world below me looking up at me/Leave the sun behind me, and watch the clouds as they sadly pass me by/And I'm in perpetual motion and the world below doesn't matter much to me", half: ["The Kinks", "The Beatles"], fullanswer: "This Time Tomorrow - The Kinks", songFile: "samp4"},
	{id: 5, question: "Who is the artist of this song?", options: ["Brockhampton", "Lil Uzi Vert", "Kanye West", "Run the Jewels"], answer: "Brockhampton", lyrics: "Keep a gold chain on my neck/Fly as a jet/Boy, better treat me with respect/Keep a gold chain on my neck/Fly as a jet/Boy, better treat me with respect/(Keep up the chain)", half: ["Brockhampton", "Lil Uzi Vert"], fullanswer: "GOLD - Brockhampton", songFile: "samp5"},
	{id: 6, question: "What is the name of this song?", options: ["Many Lives - 49 MP", "He Poos Clouds", "An Animal In Your Care", "Should Invest"], answer: "Many Lives - 49 MP", lyrics: "I picture a man who lives in the past/He keeps a book of photographs/Of his younger self, clairvoyant self!/(Son! You should invest!)", half: ["Many Lives - 49 MP", "He Poos Clouds"], fullanswer: "Many Lives - 49 MP - Owen Palette", songFile: "samp6"},
	{id: 7, question: "Who is the artist of this song?", options: ["Burial", "Monolake", "Holy Other", "Distance"], answer: "Burial", lyrics: "Holding you/Couldn't be alone/Loving you/Couldn't be alone/Kissing you/Tell me how can you, tell me I belong", half: ["Burial", "Holy Other"], fullanswer: "Archangel - Burial", songFile: "samp7"},
	{id: 8, question: "What is the name of this song?", options: ["Build a Fire", "Prom Song", "Fire on the Mountain", "What's Right"], answer: "Build a Fire", lyrics: "I'm gonna build a fire and die/One that don't care if i'm dead or alive/Show em all I've done and what's right/And they'll use it all as a guide", half: ["Build a Fire", "What's Right"], fullanswer: "Build a Fire - Pile", songFile: "samp8"},
	{id: 9, question: "Who is the artist of this song?", options: ["Bruce Springsteen", "Garth Brooks", "Mick Jagger", "David Byrne"], answer: "Bruce Springsteen", lyrics: "We sit in the car outside your house/I can feel the heat coming 'round/I go to put my arm around you/And you give me a look like I'm way out of bounds/Well you let out one of your bored sighs/Well lately when I look into your eyes/Down, down, down, down/I'm goin down", half: ["Bruce Springsteen", "Garth Brooks"], fullanswer: "I'm Going Down - Bruce Springsteen", songFile: "samp9"},
	{id: 10, question: "Who is the artist of this song?", options: ["Cat Stevens", "Neil Young", "Mick Jagger", "Rod Stewart"], answer: "Cat Stevens", lyrics: "In the midnight moonlight/I'll be walking a long and lonely mile/And every time I do/I keep seeing this picture of you", half: ["Cat Stevens", "Rod Stewart"], fullanswer: "Here Comes my Baby - Cat Stevens", songFile: "samp10"},
	{id: 11, question: "Who is the artist of this song?", options: ["Angel Olsen", "Kate Bush", "Joanna Newsom", "Agnes Obel"], answer: "Angel Olsen", lyrics: "I see an elevator/A moment I am above/I look for you or someone/Who can still remind me of/The tight grip and the sun lick/And the calm way of all things summer/When it's all here/And it's all new/And you're not hungover", half: ["Angel Olsen", "Agnes Obel"], fullanswer: "White Fire - Angel Olsen", songFile: "samp11"},
	{id: 12, question: "What is the name of this song?", options: ["The Night and the Liquor", "Ash Wednesday", "I See Your Sister", "Night's End"], answer: "The Night and the Liquor", lyrics: "And now the night and the liquor wear off/I see your sister more clear/Now that the sun has warmed the sky/Won't you sleep, my lady", half: ["The Night and the Liquor", "Night's End"], fullanswer: "The Night and the Liquor - Elvis Perkins", songFile: "samp12"},
	{id: 13, question: "Who is the artist of this song?", options: ["Dead Kennedys", "FUGAZI", "The Clash", "The Sex Pistols"], answer: "Dead Kennedys", lyrics: "Zen fascists will control you/Hundred percent natural.You will jog for the master race/And always wear a happy face/Close your eyes, can't happen here/Big Bro' on white horse is near/The hippies won't come back, you say/Mellow out or you will pay", half: ["Dead Kennedys", "The Clash"], fullanswer: "California Uber Alles - Dead Kennedys", songFile: "samp13"},
	{id: 14, question: "What is the name of this song?", options: ["The Blackest Crow", "Letters Made of Gold", "Heart of Glass", "My Dying Day"], answer: "The Blackest Crow", lyrics: "The crow that is so black, my love, will surely turn to white/If ever I prove false to you, bright day return to night/Bright day return to night, my love, the elements will mourn/If ever I prove false to you, the seas will rage and burn.", half: ["The Blackest Crow", "Letters Made of Gold"], fullanswer: "The Blackest Crow - Traditional", songFile: "samp14"},
	{id: 15, question: "Who is the artist of this song?", options: ["Shabazz Palaces", "Aesop Rock", "Kendrick Lamar", "The Roots"], answer: "Shabazz Palaces", lyrics: "Hey, here we stand/Slave to network's master plans/Swag's the brand, open the can/Change off, still y'all never ran/I brag, I boast, I kill, I coast, I toast to cake and crime/Doin' the most, a stronger dose, a king at leisure time", half: ["Shabazz Palaces", "The Roots"], fullanswer: "An Echo from the Hosts that Profess Infinitum - Shabazz Palaces", songFile: "samp15"},
	{id: 16, question: "Who is the artist of this song?", options: ["The Rolling Stones", "The Velvet Underground", "The Who", "The Beatles"], answer: "The Rolling Stones", lyrics: "'There's no time to lose', I heard her say/Catch your dreams before they slip away/Dying all the time/Lose your dreams and you will lose your mind/Ain't life unkind?", half: ["The Rolling Stones", "The Velvet Underground"], fullanswer: "Ruby Tuesday - The Rolling Stones", songFile: "samp16"},
	{id: 17, question: "Who is the artist of this song?", options: ["Bauhaus", "The Cure", "Siouxsie and the Banshees", "Echo and the Bunnymen"], answer: "Bauhaus", lyrics: "All we ever wanted was everything/All we ever got was cold/Get up, eat jelly, sandwich bars and barbed wire/And squash every week into a day", half: ["Bauhaus", "The Cure"], fullanswer: "All We Ever Wanted was Everything - Bauhaus", songFile: "samp17"},
	{id: 18, question: "What is the name of this song?", options: ["Love Will Tear Us Apart Again", "The Killing Moon", "Isolation", "Disorder"], answer: "Love Will Tear Us Apart Again", lyrics: "Why is the bedroom so cold/Turned away on your side?/Is my timing that flawed, our respect run so dry?/Yet theres still this appeal/That weve kept through our lives/Love, love will tear us apart again", half: ["Love Will Tear Us Apart Again", "The Killing Moon"], fullanswer: "Love Will Tear Us Apart Again - Joy Division", songFile: "samp18"},
	{id: 19, question: "What is the name of this song?", options: ["Within You Without You", "Norwegian Wood", "Tomorrow Never Knows", "Sea of Green"], answer: "Within You Without You", lyrics: "Try to realize it's all within yourself, no-one else can make you change/And to see you're really only very small/And life flows on within you and without you", half: ["Within You Without You", "Sea of Green"], fullanswer: "Within You Without You - The Beatles", songFile: "samp19"},
	{id: 20, question: "Who is the artist of this song?", options: ["Talking Heads", "Devo", "Minutemen", "Fine Young Cannibals"], answer: "Talking Heads", lyrics: "And you may ask yourself/How do I work this?/And you may ask yourself/Where is that large automobile?/And you may tell yourself/This is not my beautiful house!/And you may tell yourself/This is not my beautiful wife!", half: ["Talking Heads", "Fine Young Cannibals"], fullanswer: "Once in a Lifetime - Talking Heads", songFile: "samp20"},
	{id: 21, question: "Who is the artist of this song?", options: ["Agnes Obel", "Kate Bush", "Joanna Newsom", "The Knife"], answer: "Agnes Obel", lyrics: "Can you walk on the water with I, you and I?/'Because your blood's running cold' said the familiar, true to life/Can you walk on the water with I, you and I?", half: ["Agnes Obel", "The Knife"], fullanswer: "Familiar - Agnes Obel", songFile: "samp21"},
	{id: 22, question: "Who is the artist of this song?", options: ["Radiohead", "Tool", "Coldplay", "Smashing Pumpkins"], answer: "Radiohead", lyrics: "But it got edited, fucked up/Strangled, beaten up/Used as a photo in Time magazine/Buried in a burning black hole in Devon/I don't know why I feel so tongue tied/Don't know why I feel so skinned alive", half: ["Radiohead", "Smashing Pumpkins"], fullanswer: "Myxomatosis - Radiohead", songFile: "samp22"},
	{id: 23, question: "Who is the artist of this song?", options: ["David Bowie", "Peter Gabriel", "David Byrne", "Scott Walker"], answer: "David Bowie", lyrics: "I will sit right down, waiting for the gift of sound and vision/And I will sing, waiting for the gift of sound and vision/Drifting into my solitude, over my head/Don't you wonder sometimes/'Bout sound and vision", half: ["David Bowie", "Peter Gabriel"], fullanswer: "Sound and Vision - David Bowie", songFile: "samp23"},
	{id: 24, question: "Who is the artist of this song?", options: ["Kate Bush", "Agnes Obel", "Joanna Newsom", "The Knife"], answer: "Kate Bush", lyrics: "You don't want to hurt me/But see how deep the bullet lies./Unaware I'm tearing you asunder./Ooh, there is thunder in our hearts./Is there so much hate for the ones we love?", half: ["Kate Bush", "The Knife"], fullanswer: "Running up That Hill - Kate Bush", songFile: "samp24"},
	{id: 25, question: "Who is the artist of this song?", options: ["El-P", "Beastie Boys", "Deltron 3030", "MF Doom"], answer: "El-P", lyrics: "Fuck my life already/Fuck the law, fuck the sun, say goodnight already/You fucking spam-bots selling shit, alright already/We get it you getting that fetti, oh Jesus Christ already", half: ["El-P", "Beastie Boys"], fullanswer: "Drones over Brooklyn - El-P", songFile: "samp25"},
	{id: 26, question: "Who is the artist of this song?", options: ["Bad Bad Not Good", "The Bad Plus", "Nat King Cole", "Kurt Elling"], answer: "Bad Bad Not Good", lyrics: "Oh, if I had another chance/To make you stay/Cause when you ran away/I knew just what you were thinking that day/You just didn't love me like I do/Like I love you/The sad thing is we're better off this way", half: ["Bad Bad Not Good", "The Bad Plus"], fullanswer: "Time Moves Slow - Bad Bad Not Good", songFile: "samp26"},
	{id: 27, question: "Who is the artist of this song?", options: ["The Pixies", "The Violent Femmes", "Modest Mouse", "Sonic Youth"], answer: "The Pixies", lyrics: "I was swimmin' in the Caribbean/Animals were hiding behind the rock/Except the little fish/But they told me, he swears/Tryin' to talk to me koi koy/Where is my mind", half: ["The Pixies", "The Violent Femmes"], fullanswer: "Where is my Mind - The Pixies", songFile: "samp27"},
	{id: 28, question: "What is the name of this song?", options: ["Gloria", "Horses", "Lola", "Redondo Beach"], answer: "Gloria", lyrics: "And her name is G-l-o-are-i-a/G-l-o-are-i-a, Gloria", half: ["Gloria", "Horses"], fullanswer: "Gloria - Patti Smith", songFile: "samp28"},
	{id: 29, question: "Who is the artist of this song?", options: ["The Velvet Underground", "The Rolling Stones", "The Who", "The Beatles"], answer: "The Velvet Underground", lyrics: "Yknow that, women, never really faint/And that villains always blink their eyes, woo!/And that, yknow, children are the only ones who blush!/And that, life is just to die!", half: ["The Velvet Underground", "The Rolling Stones"], fullanswer: "Sweet Jane - The Velvet Underground", songFile: "samp29"},
	{id: 30, question: "Who is the artist of this song?", options: ["The Beatles", "The Rolling Stones", "Cat Stevens", "The Velvet Underground"], answer: "The Beatles", lyrics: "Your day breaks, your mind aches.You find that all the words of kindness linger on/When she no longer needs you/She wakes up, she makes up/She takes her time and doesn't feel she has to hurry/She no longer needs you", half: ["The Beatles", "The Rolling Stones"], fullanswer: "For No-one - The Beatles", songFile: "samp30"},
];



